### ISSUE TITLE
Add contentType to options 

### ISSUE THREAD

**Issue by grafikchaos** [MantaCodeDevs/multer-azure-storage#4]
First, thanks for the great module! It was super easy to plug and play.

I ran into an issue of my image files always downloading instead of being able to be visible in the browser and traced it back to the Content-Type being defaulted to `application/octet-stream` when it ideally should be set to the file's mime type. I noticed there are already a couple forks of this project that have fixed this issue and don't want to pile on. Would you consider pulling in changes from either [CheryCheryBoom's fork](https://github.com/CheryCheryBoom/multer-azure-storage/commit/98ea9477e2f4fe9aaa0f9258ecc652332ed8e220) or [calvium's branch](https://github.com/calvium/multer-azure-storage/commit/72e1693cb83fbe940f465368a01c808b6db99613) to address the missing `options` and `contentType` settings?

For reference:

https://azure.github.io/azure-storage-node/BlobService.html#createWriteStreamToBlockBlob

**Comment by akoso** [comment]
Thanks for the info. We have merged calvium's branch, and published the updated version to npm as 0.1.3
